### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anicetoclucas** [anicetoclucas/Cax-bot#2]
Major
- [ ] Adicionar suporte a comandos de barra

Minor
- [ ] Adicionar mais comandos que utilizam a manipulação de imagem no Jimp
- [ ] Gravar canal de voz
